### ISSUE TITLE
Changing scss file is not cause assets recombine

### ISSUE THREAD

**Issue by s4urp8n** [christianWilling/Scss#1]
I wrote this in layout file

``` html
<link href="{{ [
            'assets/styles/normalize.css/normalize.css',
            'assets/styles/animate.css/animate.css',
            'assets/styles/font-awesome/font-awesome.css',
            'assets/styles/app.scss'
        ] | theme }}" rel="stylesheet">
```

If I change something in css-file or scss from list above and update some project page - the changes displays, if  I change file imported from app.scss - no.
I think changing of imported scss files is not cause assets recombine

app.scss

``` scss
@import "layout/variables";
@import "layout/functions";
@import "layout/mixins";
@import "layout/reset";
@import "layout/keyframes";
```

**Comment by christianWilling** [comment]
Yes i know this Problem this comes from October CMS and it's exactly the same with less files this comes from the caching function in the asset combiner.

I will lock to fix this later but currently I don't have the time to do that. And I'm not sure if I can fix this or if October CMS must change something in this class but than I will create an issue there.

**Comment by christianWilling** [comment]
i created an issue for the problem

octobercms/october#1778
