### ISSUE TITLE
Parser error - "bootstrap": "v4.0.0-alpha.2"

### ISSUE THREAD

**Issue by cr2a-graphique** [christianWilling/Scss#12]
After compile :
Undefined variable $i: line: 32 

maybe same as : https://github.com/leafo/scssphp/issues/449

Can't compile Bootstrap-4-Alpha
Please can you help ?

**Comment by christianWilling** [comment]
yap this is exactly the same error so we need to wait for an fix for that.

if the fix is out i will make an new version with the fix included,

**Comment by cr2a-graphique** [comment]
a fix is available here i think : https://github.com/leafo/scssphp/compare/master...FMCorz:issue-446 ?

**Comment by christianWilling** [comment]
you can use this fix for you if it works but for the plugin i will wait if the pr is merged https://github.com/leafo/scssphp/pull/453

**Comment by cr2a-graphique** [comment]
ok i try, then, if its not good, i w8 too

**Comment by cr2a-graphique** [comment]
YEss it works good
