### ISSUE TITLE
Undefined variable $theme-folder

### ISSUE THREAD

**Issue by IrealiTY** [christianWilling/Scss#13]
The newest version dropped this error on me:

`An exception has been thrown during the rendering of a template ("Undefined variable $theme-folder: line: 2").`

**Comment by IrealiTY** [comment]
Did it perhaps change to: $themePath?

**Comment by christianWilling** [comment]
This Plugin isnt Support anymore the function is now in octobercms core

**Comment by IrealiTY** [comment]
hm, could you elaborate what you mean?
SCSS is not working anymore with october? or is there now a different way to use theme-folder?

Didn't see any news from october for SCSS support :)

**Comment by IrealiTY** [comment]
Ah I got it figured out.

```
    'enableAssetDeepHashing' => true,
in `config/cms.php` file and include any SCSS files in an array like so: `<link href="{{ ['assets/scss/app.scss'] | theme }}" rel="stylesheet">`
```

Thanks for keeping your plugin alive for the time period!
