### ISSUE TITLE
Relative paths not works?

### ISSUE THREAD

**Issue by amdad** [christianWilling/Scss#3]
I need to use `/themes/mytheme/assets/images/image.jpg` instead of `../images/image.jpg`

**Comment by christianWillingBgpEmedia** [comment]
yes but you can use the theme-folde variabel in scss :)

**Comment by christianWilling** [comment]
hi sorry for the late response.

yes you need to use the absolute path but yxou can usethe theme-folder variable wich is set by the plugin.

**Comment by amdad** [comment]
Ok, that's solution. Thanks!
