### ISSUE TITLE
After enabling assets minify getting error

### ISSUE THREAD

**Issue by samuelpatro** [christianWilling/Scss#4]
An exception has been thrown during the rendering of a template ("Call to undefined method [registerFilter]").

**Comment by christianWilling** [comment]
can you send mir the error log please so i can lock to fix the problem.

sry for the long response time i had an problem with my mail server.

**Comment by samuelpatro** [comment]
http://pastebin.com/kLYGs5eM

**Comment by christianWilling** [comment]
hi,

i fixed the problem update the plugin and the error should be gone.
