### ISSUE TITLE
Relative paths for images

### ISSUE THREAD

**Issue by IrealiTY** [christianWilling/Scss#5]
Hello,
 I get the feeling that there some issues with relative paths for the images inside the scss.

How I include main main scss file
`<link href="{{ ['assets/scss/main.scss']|theme }}" rel="stylesheet">`

One of my sub scss files has the following declaration:
`background-image: url('../img/header_slider_1.png');`

The system tells me though:
`http://domain.com/img/header_slider_1.png 404 (Not Found)`

While the image is in:
`domain.com/public/themes/rainlab-vanilla/assets/img`
the scss file is in 
`domain.com/public/themes/rainlab-vanilla/assets/scss`
and which includes some files in the sub foldersm, the folder structure is:
![image](https://cloud.githubusercontent.com/assets/1223686/16382094/ad1bf1c4-3c7f-11e6-80c0-0a37ed0e4b05.png)

**Comment by christianWilling** [comment]
hi

the problem is that the php compiler can't work with other relative paths.

but you can use the `$theme-folder` variable from that is set by the plugin.

i hope this works for you :)

**Comment by IrealiTY** [comment]
Oh,I see. Do you refer to this https://octobercms.com/docs/markup/filter-theme when you mean the theme-folder? Or did I miss something?

**Comment by christianWilling** [comment]
no i mean that the plugin set's an scss variable `$theme-folder`. In your case with the conent `/themes/rainlab-vanilla/` so you need 
`background-image: url(' $theme-folde + "assets/img/header_slider_1.png"');`

**Comment by IrealiTY** [comment]
OH I didn't know this was possible, thanks :)
I was looking for "in-scss-variables" but couldn't find any references in the doc's
I'll try that, thanks

**Comment by christianWilling** [comment]
yes i need to add this to the documentation of the plugin.

**Comment by IrealiTY** [comment]
I'm not sure I'm using it correct.
Snippet from my scss:

```
.banner {
  background-image: url('$theme-folder + "assets/img/header_slider_1.png"');
  height: 430px;
  margin-bottom: -80px;
  position: relative;
  top: -80px;

  .banner-content {
    text-align: center;
  }
```

results in:
`domain.com/combine/$theme-folder%20+%20%22assets/img/header_slider_1.png%22 404 (Not Found)`

EDIT:

Nevermind... I was to dump to use interpolation:
`#{$theme-folder}/assets.....`
did the trick

**Comment by christianWilling** [comment]
you need to use it like 
`background-image: url($theme-folder + "assets/img/header_slider_1.png");`
