### ISSUE TITLE
Stopped working?

### ISSUE THREAD

**Issue by McSuckelaer** [christianWilling/Scss#6]
Is it just me, or did this plugin just simply stopped working?

I had been working on a project and everything worked fine. Now i started working on a new project, i install the plugin and it simply does not work. 

`<link href="{{ [
            'assets/scss/base.scss'
        ]|theme }}" rel="stylesheet">` ( the file is there, no problem ) generates a stylesheet in combine, like always, but when try to open that in dev inspect i get a 500 error.

**Comment by christianWilling** [comment]
Hi

Can you please send me the error log ?

Than I can try to fix the problem.

**Comment by yuqinz** [comment]
leafo/scssphp wasn't install for some reason?

**Comment by christianWilling** [comment]
that is an intresting error because leafo/scssphp is in the require-dev from the kriswallsmith/assetic.

so i think the package should be there or have i an logic error in this ?

**Comment by christianWilling** [comment]
so I had an logic error and now know why there is this problem and i had fix this in the pr that the octobercms core support scss

https://github.com/christianWilling/Scss/pull/7
