### ISSUE TITLE
Class 'Leafo\ScssPhp\Compiler' not found

### ISSUE THREAD

**Issue by sil218** [christianWilling/Scss#9]
Hi, I am getting this error after install the plugin

**Comment by robverhoef** [comment]
@sil218 Here is a workaround (probably not a fix): create a file named composer.json in plugins/willing/scss and put this into it:
{
    "name": "willing/scss",
    "type": "october-plugin",
    "description": "Adds SCSS support to the standard October resource combiner",
    "homepage": "http://octobercms.com",
    "keywords": ["october", "cms", "willing", "sass", "scss"],
    "authors": [
        {
            "name": "Christian Willing"
        }
    ],
    "require": {
        "leafo/scssphp": "dev-master"
    }
}

Then in a terminal screen cd to this folder plugins/willing/scss and enter 'composer install'. After this has finished you should be able to continue.
Note: there is currently a bug in scssphp https://github.com/leafo/scssphp/issues/446 that prevents compiling foundation-sites 6.2.3

**Comment by amdad** [comment]
New installations of plugin, are broken. Almost empty. So nothing works. Any fix release?

**Comment by christianWilling** [comment]
So the Pr that this will get to the kore of Octobercms take some time so i created an update wich includes the composer.json and the vendor folder

**Comment by amdad** [comment]
Why those files are missing in new version? Former works.

**Comment by christianWilling** [comment]
short version i had an logic error 

long version is here

https://github.com/christianWilling/Scss/pull/7

**Comment by sil218** [comment]
it works now, thanks you so much!
